[2024-04-12T10:43:29.828+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T10:43:29.842+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_project_1.postgres_to_s3 manual__2024-04-12T10:43:28.218159+00:00 [queued]>
[2024-04-12T10:43:29.850+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_project_1.postgres_to_s3 manual__2024-04-12T10:43:28.218159+00:00 [queued]>
[2024-04-12T10:43:29.852+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-12T10:43:29.864+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-04-12 10:43:28.218159+00:00
[2024-04-12T10:43:29.870+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_project_1', 'postgres_to_s3', 'manual__2024-04-12T10:43:28.218159+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dag_project_1.py', '--cfg-path', '/tmp/tmpf0kvefd9']
[2024-04-12T10:43:29.872+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1000) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-12T10:43:29.872+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask postgres_to_s3
[2024-04-12T10:43:29.873+0000] {standard_task_runner.py:63} INFO - Started process 1001 to run task
[2024-04-12T10:43:29.920+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_project_1.postgres_to_s3 manual__2024-04-12T10:43:28.218159+00:00 [running]> on host c2a9f453f2e0
[2024-04-12T10:43:29.993+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_project_1' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T10:43:28.218159+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T10:43:28.218159+00:00'
[2024-04-12T10:43:29.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T10:43:30.007+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-04-12T10:43:30.017+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-04-12T10:43:30.036+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T10:43:30.037+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_project_1.py", line 24, in postgres_to_s3
    cursor.execute("select * from NewbornBaby where date >= %s and date < %s",
psycopg2.errors.UndefinedColumn: column "date" does not exist
LINE 1: select * from NewbornBaby where date >= '20240412' and date ...
                                        ^
HINT:  Perhaps you meant to reference the column "newbornbaby.name".

[2024-04-12T10:43:30.049+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_project_1, task_id=postgres_to_s3, execution_date=20240412T104328, start_date=20240412T104329, end_date=20240412T104330
[2024-04-12T10:43:30.066+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 119 for task postgres_to_s3 (column "date" does not exist
LINE 1: select * from NewbornBaby where date >= '20240412' and date ...
                                        ^
HINT:  Perhaps you meant to reference the column "newbornbaby.name".
; 1001)
[2024-04-12T10:43:30.089+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T10:43:30.101+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T10:43:30.104+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
